In [1]:
import gridworld
import numpy as np


world=gridworld.GridWorld()
minus_inf=-99
value_tables=np.full((world.WORLD_HEIGHT,world.WORLD_WIDTH),minus_inf,dtype=float)
optimal_action=np.full((world.WORLD_HEIGHT,world.WORLD_WIDTH),-1)
value_tables[world.GOAL[0]][world.GOAL[1]]=0

In [2]:
def assign_value(current_state):
    action_values=np.array([0,0,0,0])
    for action in world.ACTIONS:
        new_state,reward=world.step(current_state,action)
        if(world.WIND[new_state[0]]==0):
            action_values[action]=reward+value_tables[new_state[0]][new_state[1]]
        else:
            if(action==0 or action==1):
                if(new_state[1]==current_state[1]):
                    state2=value_tables[new_state[0]][new_state[1]]
                    state8=value_tables[new_state[0]][max(0,new_state[1]-world.WIND[new_state[0]])]
                else:
                    state8=value_tables[new_state[0]][new_state[1]]
                    state2=value_tables[new_state[0]][current_state[1]]
            elif(action==3):
                if(current_state[1]==world.WORLD_WIDTH-1):
                    state2=value_tables[current_state[0]][current_state[1]]
                    state8=value_tables[current_state[0]][max(0,current_state[1]-world.WIND[current_state[0]])]
                else:
                    state2=value_tables[current_state[0]][current_state[1]+1]
                    state8=value_tables[current_state[0]][max(0,1+current_state[1]-world.WIND[current_state[0]])]
            elif(action==2):
                if(current_state[1]==0):
                    state2=value_tables[current_state[0]][current_state[1]]
                    state8=value_tables[current_state[0]][max(0,current_state[1]-world.WIND[current_state[0]])]
                else:
                    state2=value_tables[current_state[0]][current_state[1]-1]
                    state8=value_tables[current_state[0]][max(0,-1+current_state[1]-world.WIND[current_state[0]])]
            action_values[action]=reward+(1-world.WIND_PROB)*state2+(world.WIND_PROB)*state8
    max_val, max_action=action_values[0],0
    for i in range (4):
        if(action_values[i]>max_val): max_val,max_action=action_values[i],i
    return max_val,max_action

In [3]:
for k in range(10000):
    for i in range (world.WORLD_HEIGHT):
        for j in range (world.WORLD_WIDTH):
            if [i,j] not in (world.obstacles+[world.GOAL]):
                if(value_tables[i][j]<(assign_value([i,j])[0])):
                    value_tables[i][j],optimal_action[i][j]=assign_value([i,j])[0],assign_value([i,j])[1]


In [4]:
print(optimal_action)

[[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1]
 [ 3  3  3  3  1  1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0 -1  1  1  1  1  1  1  1  1  1  1  1]
 [ 0  0  0 -1  3  3  3  3  3  3  3  3  3  1  1]
 [ 0  0  0  3  0  0  0  0  0  0  0  0  1  1  1]
 [ 0  0  0  0  0  0  0  0  0  1  1  1  1  1  1]
 [ 0  0  0  0  0  0  0  3  3  1  1  1  1  2  2]
 [ 0  0  0 -1  3  3  3  0 -1  1  1  1  2  2  2]
 [ 0  0  0 -1  0  0  0  0 -1  3  3 -1  2  2  2]
 [ 0  0  0 -1  0  0  0  0 -1  0  0  0  0  0  0]]


In [5]:
print(value_tables)

[[-20. -19. -18. -17. -16. -15. -14. -13. -12. -11. -10.  -9.  -8.  -7.
   -7.]
 [-19. -18. -17. -16. -15. -14. -13. -12. -11. -10.  -9.  -8.  -7.  -6.
   -6.]
 [-20. -19. -18. -99. -14. -13. -12. -11. -10.  -9.  -8.  -7.  -6.  -5.
   -5.]
 [-21. -20. -19. -99. -13. -12. -11. -10.  -9.  -8.  -7.  -6.  -5.  -4.
   -4.]
 [-22. -21. -20. -19. -14. -13. -12. -11. -10.  -9.  -8.  -7.  -3.  -3.
   -3.]
 [-23. -22. -21. -20. -19. -14. -13. -12. -11.  -8.  -3.  -2.  -2.  -3.
   -3.]
 [-24. -23. -23. -22. -21. -19. -18. -13.  -8.  -3.  -2.  -1.  -2.  -2.
   -3.]
 [-25. -24. -24. -99. -21. -20. -19. -18. -99.  -2.  -1.   0.  -1.  -2.
   -3.]
 [-26. -25. -25. -99. -22. -21. -20. -19. -99.  -1.   0.   0.   0.  -1.
   -2.]
 [-27. -26. -26. -99. -23. -22. -21. -20. -99.  -2.  -1.   0.  -1.  -2.
   -3.]]


In [6]:
current_state=world.START
total_reward=0
cnt=1
print("Initial Co-ordinate : ",current_state)
while(current_state!=world.GOAL):
    new_state,reward=world.step(current_state,optimal_action[current_state[0]][current_state[1]])
    print("Co-ordinate at step ",cnt," : ",new_state)
    total_reward+=reward
    cnt+=1
    current_state=new_state
print("GOAL REACHED in most optimal way.")
print("Maximum possible reward : ",total_reward)

Initial Co-ordinate :  [6, 1]
Co-ordinate at step  1  :  [5, 0]
Co-ordinate at step  2  :  [4, 0]
Co-ordinate at step  3  :  [3, 0]
Co-ordinate at step  4  :  [2, 0]
Co-ordinate at step  5  :  [1, 0]
Co-ordinate at step  6  :  [1, 1]
Co-ordinate at step  7  :  [1, 2]
Co-ordinate at step  8  :  [1, 3]
Co-ordinate at step  9  :  [1, 4]
Co-ordinate at step  10  :  [2, 4]
Co-ordinate at step  11  :  [3, 4]
Co-ordinate at step  12  :  [3, 5]
Co-ordinate at step  13  :  [3, 6]
Co-ordinate at step  14  :  [3, 7]
Co-ordinate at step  15  :  [3, 8]
Co-ordinate at step  16  :  [3, 9]
Co-ordinate at step  17  :  [3, 10]
Co-ordinate at step  18  :  [3, 11]
Co-ordinate at step  19  :  [3, 12]
Co-ordinate at step  20  :  [3, 13]
Co-ordinate at step  21  :  [4, 12]
Co-ordinate at step  22  :  [5, 10]
Co-ordinate at step  23  :  [6, 9]
Co-ordinate at step  24  :  [7, 9]
Co-ordinate at step  25  :  [8, 9]
Co-ordinate at step  26  :  [8, 10]
Co-ordinate at step  27  :  [8, 11]
GOAL REACHED in most optim

In [7]:
import cv2 as cv

img=cv.imread("grid.png")
img=cv.resize(img,(1600,1100))
current_state=world.START
y=(current_state[0]+1)*50+(current_state[0]+2)*50
x=(current_state[1]+1)*50+(current_state[1]+2)*50
cv.circle(img,(x,y),40,(0,0,255),-1)
while(current_state!=world.GOAL):
    new_state,reward=world.step(current_state,optimal_action[current_state[0]][current_state[1]])
    y=(new_state[0]+1)*50+(new_state[0]+2)*50
    x=(new_state[1]+1)*50+(new_state[1]+2)*50
    cv.circle(img,(x,y),40,(0,0,255),-1)
    current_state=new_state
cv.imwrite("path.jpeg",img)

True